support php8.0
php-casbin/psr3-bridge pull request #1
Opened 2022-02-04 05:43 UTC by shine96

support php8.0

2022-02-04 11:09 UTC, hsluoyz commented
@leeqvip

2022-02-05 11:56 UTC, leeqvip requested changes

2022-02-05 11:56 UTC, leeqvip commented on composer.json
> +        "psr/log": "^2.0"
This should be compatible with versions before php8.
```
"psr/log": "^1.1|^2.0|^3.0"
```

2022-02-05 12:04 UTC, merged

2022-02-05 12:09 UTC, leeqvip commented
:tada: This PR is included in version 1.3.1 :tada:

The release is available on [GitHub release](https://github.com/php-casbin/psr3-bridge/releases/tag/v1.3.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: